clear all; clc;
dataFolder = '/home/wuye/D_disk/MTE_dMRI/XYQ/proc';
TE = [75 85 95 105 115];
fdwi    = arrayfun(@(x)fullfile(dataFolder,strcat('MTE_',num2str(x),'_align_center_denoise_unring_preproc_epi_unbiased2_in_T1.nii.gz')),TE,'UniformOutput',false);
fbval   = arrayfun(@(x)fullfile(dataFolder,strcat('MTE_',num2str(x),'_align_center_denoise_unring_preproc_epi_unbiased2_in_T1.bval')),TE,'UniformOutput',false);
fbvec   = arrayfun(@(x)fullfile(dataFolder,strcat('MTE_',num2str(x),'_align_center_denoise_unring_preproc_epi_unbiased2_in_T1.bvec')),TE,'UniformOutput',false);
ft2r    = fullfile(dataFolder,'ME_SMSIx_ROI','T2.nii.gz');
fmask   = fullfile(dataFolder,'MTE_mask_ROI.nii.gz');
ME_SMSIx(fdwi,fbval,fmask,TE,fullfile(dataFolder,'ME_SMSIx_ROI'),spectrum='scheme/new_spectrum.mat');
ME_SIx(fdwi,fbvec,fbval,ft2r,fmask,TE,fullfile(dataFolder,'ME_SIx_ROI'),spectrum='scheme/new_spectrum.mat');